name: CI - ExecuÃ§Ã£o dos testes DemoQA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ§° Instalar dependÃªncias do Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo apt-get install -y wget gnupg2
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: ğŸ”§ Configurar ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: â˜• Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ğŸ” Verificar instalaÃ§Ã£o
        run: |
          google-chrome --version
          chromedriver --version
          java -version

      - name: ğŸ§ª Executar testes com Maven
        env:
          HEADLESS: true
        run: |
          mvn clean test -Dtest="RunCucumberTest" -Dheadless=true

      - name: ğŸ“Š Salvar RelatÃ³rios dos Testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/

